import React, { useState, useEffect } from 'react'
import "@fortawesome/fontawesome-svg-core/styles.css";

import Head from 'next/head'
import styles from '../styles/Home.module.scss'
import { Container, Row, Col } from 'react-bootstrap'
import { FontAwesomeIcon } from '@fortawesome/react-fontawesome'
import { faTimes, faCompass } from '@fortawesome/free-solid-svg-icons'
import { faGithub, faInstagram } from '@fortawesome/free-brands-svg-icons'

export default function Home() {

  const [scrollTo, setScrollTo] = useState("top")
  const [showMenu, setShowMenu] = useState(false)

  useEffect(() => {
    const anchor = document.querySelector(`#${scrollTo}`)
    anchor.scrollIntoView({ behavior: "smooth", block: "center" })
    setShowMenu(false)
  }, [scrollTo])


  const Link = ({ title, id }) => {
    return (
      <div className={styles.link} onClick={() => setScrollTo(id)}>{title}</div>
    )
  }

  const links = [
    { title: "Top", id: "top" },
    { title: "About Me", id: "about-me" },
    { title: "Experience", id: "experience" },
    // {title: "About Me", id="about-me"},
  ]


  const Section = ({ id, title, content }) => {
    return (
      <div id={id} className={styles.section}>
        <h1>
          {title}
        </h1>
        <div>
          {content}
        </div>
      </div>
    )
  }
  const sections = [
    {
      title: "About Me", id: "about-me", content: `Once when I was six years old I saw a magnificent picture in a book, called True
    Stories from Nature, about the primeval forest. It was a picture of a boa constrictor
    in the act of swallowing an animal. Here is a copy of the drawing.
    In the book it said: "Boa constrictors swallow their prey whole, without chewing
    it. After that they are not able to move, and they sleep through the six months that
    they need for digestion.' ` },
    {
      title: "Experience", id: "experience", content: `But it happened that after walking for a long time through sand, and rocks, and
    snow, the little prince at last came upon a road. And all roads lead to the abodes of
    men.
    "Good morning," he said.
    He was standing before a garden, all a−bloom with roses.
    "Good morning," said the roses.
    The little prince gazed at them. They all looked like his flower.
    "Who are you?" he demanded, thunderstruck.
    "We are roses," the roses said.
    And he was overcome with sadness. His flower had told him that she was the only
    one of her kind in all the universe. And here were five thousand of them, all alike,
    in one single garden!` },


  ]

  return (
    <div >
      <Head>
        <title>David Visotsky </title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main} id="top">
        <div onClick={() => setShowMenu(!showMenu)} style={{ margin: "0", padding: "0", position: "absolute", top: "20px", right: "3rem", fontSize: "25px", transition: "0.4s", transform: `${showMenu ? "rotate( 90deg)" : "rotate(0)"}`, transformOrigin: "50% 45%" }}>
          <FontAwesomeIcon icon={faCompass} />
        </div>
        <Container>

          <Row style={{ justifyContent: "center", padding: "0", overflow: "hidden" }}>

            <div className={`${styles.banner} ${showMenu ? styles.show : ""}`}>
              <div className={styles.menu}>
                {links.map((l) => (
                  <Link key={l.id} title={l.title} id={l.id} />
                ))}
                <div style={{ padding: "20px" }} onClick={() => setShowMenu(false)}> <FontAwesomeIcon size="1x" icon={faTimes} />
                </div>
              </div>
            </div>

            {/* <Col lg={2} sm={3}>

              <h1 className={styles.title}>
                David Visotsky
              </h1>
              <h2>Software Engineer</h2>

            </Col> */}


            <Col lg={8} md={10}>
              <Row >
                <Col>
                  <Row className={styles.title}>
                    <Col lg={2} className={styles.profile}>
                    </Col>
                    <Col>
                      <h1>
                        David Visotsky
                      </h1>
                      <div>visotskydavid@gmail.com </div>
                      <div style={{ display: "flex" }}>
                        <a className={styles.link} href="https://github.com/dvisotsky" target="_blank" ><FontAwesomeIcon icon={faGithub} /></a><a href="https://www.instagram.com/david_heights/" target="_blank" className={styles.link}> <FontAwesomeIcon icon={faInstagram} /></a></div>
                    </Col>
                  </Row>
                  <div className={styles.text}>
                    Hello, thanks for stopping by.<br />
                    I'm David, a software engineer hailing from Charlotte, North Carolina.
                    I'm a web designer & front‑end developer focused on crafting clean & user‑friendly experiences,
                    I am passionate about building excellent software that improves the lives of those around me.
                  </div></Col>
              </Row>
              {sections.map((s) => (
                <Row>
                  <Col><Section id={s.id} title={s.title} />{s.content}</Col>

                </Row>
              ))}
            </Col>
          </Row>
        </Container>

      </main>

      <footer className={styles.footer}>

      </footer>
    </div >
  )
}
