import Head from 'next/head'
import styles from '../styles/Home.module.scss'
import React, { useState, useEffect } from 'react'
import { Container, Row, Col } from 'react-bootstrap'

export default function Home() {
  var name = "David Visotsky"


  // const scrollTo = (id) => {

  //   const anchor = document ? document.querySelector(`#${id}`) : null
  //   anchor.scrollIntoView({ behavior: "smooth", block: "center" })
  // }

  const [scrollTo, setScrollTo] = useState("top")

  useEffect(() => {
    const anchor = document.querySelector(`#${scrollTo}`)
    anchor.scrollIntoView({ behavior: "smooth", block: "center" })
    console.log(scrollTo)
  }, [scrollTo])


  const Link = ({ title, id }) => {
    return (
      <div className={styles.link} onClick={() => setScrollTo(id)}>{title}</div>
    )
  }

  const links = [
    { title: "Top", id: "top" },
    { title: "About Me", id: "about-me" },
    { title: "Experience", id: "experience" },
    { title: "Contact", id: "contact" },
    // {title: "About Me", id="about-me"},
  ]


  const Section = ({ id, title, content }) => {
    return (
      <div id={id}>
        <h1>
          {title}
        </h1>
        <div>
          {content}
        </div>
      </div>
    )
  }

  return (
    <div style={{ height: "100vh" }}>
      <Head>
        <title>David Visotsky</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main} id="top">
        <Container>
          <Row style={{ height: "100%" }}>
            <Col lg={2} sm={1} className={styles.banner}>
              <div className={styles.menu}>
                {links.map((l) => (
                  <Link key={l.id} title={l.title} id={l.id} />
                ))}
              </div>
            </Col>

            {/* <Col lg={2} sm={3}>

              <h1 className={styles.title}>
                David Visotsky
              </h1>
              <h2>Software Engineer</h2>

            </Col> */}


            <Col className={styles.content}>
              <Row>
                <Col>
                  <div className={styles.title}>
                    <div className={styles.profile}>
                    </div>
                    <div>

                      <h1>
                        David Visotsky
                      </h1>
                      <h2>Software Engineer</h2>
                    </div></div>
                  <div className={styles.text}>
                    Hello, thanks for stopping by.<br />
                    I'm David, a software engineer hailing from Charlotte, North Carolina.

                  </div></Col>
              </Row>
              <Row>
                <Col><Section id={"about-me"} title={"about me"} /></Col>

              </Row>
            </Col>
          </Row>
        </Container>

      </main>

      <footer className={styles.footer}>

      </footer>
    </div>
  )
}
