import Head from 'next/head'
import styles from '../styles/Home.module.css'
import { Container, Row, Col, Button } from 'react-bootstrap'

export default function Home() {
  var name = "David Visotsky"
  return (
    <div className={styles.container}>
      <Head>
        <title>David Visotsky</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <Container>
          <Row>
            <Col lg={1} sm={1}>

              <div className="styles.link">About me</div>
              <div className="styles.link">About me</div>
              <div className="styles.link">About me</div>
              <div className="styles.link">About me</div>
            </Col>

            <Col>
              <h1 className={styles.title}>
                David Visotsky
              </h1>
              <h2>Software Engineer</h2>
            </Col>


            <Col>
              <h1 className={styles.title}>
                David Visotsky
              </h1>
              <h2>Software Engineer</h2>
            </Col>

            <Col>
              <h1 className={styles.title}>
                David Visotsky
              </h1>
              <h2>Software Engineer</h2>
            </Col>
          </Row>
        </Container>

      </main>

      <footer className={styles.footer}>

      </footer>
    </div>
  )
}
